### ISSUE TITLE
Push Notification not received when app is closed

### ISSUE THREAD

**Issue by NkHAp** [phonegap/phonegap-plugin-push#167]
I am using phonegap build and in that I am using *<gap:plugin name="phonegap-plugin-push" source="npm" version="1.2.3" />* . In this I have observed that if app is not running then it doesn't receive any notification. For instance First; I am running my app and trigger a push notification from server, then app shows me notification in shades as well as batch too this case is working perfectly.

Second; If am using my app and presses home button(Android) and do other task which means app is still running and in pause state in background. If I trigger a push notification then app receive the notification and it can be seen in shades. So this case is also working fine.

Third; If my app is completely closed means no background or foreground, then if I trigger a push notification from server then nothing happens inside my app. I have tested this case with n number of push notifications but none of it worked. 

So it might be a bug that if app is not running or it's completely closed then app can't receive push notification and show in shades or in notification bar. For more specific I have also checked that their should be background service running to receive any broadcast messages which work like a broadcast receiver. 

PS: I have only tested this in Android only. I haven't tested in iOS yet.

**Comment by christocracy** [comment]
Duplicate #109 ?

**Comment by app2naklabs** [comment]
I have already checked those issues but this issue has different usecase although it might be related to previous issues in same concept but different usecase.

**Comment by christocracy** [comment]
A colleague of mine wrote a push-plugin for his http://cloudfiveapp.com build service which I believe solves your case 3.  It's a clever trick which reboots the foreground Android Activity if it was closed, then sends the push to it.

https://github.com/christocracy/push-cordova-plugin/blob/master/src/android/PushHandlerActivity.java#L34

**Comment by app2naklabs** [comment]
Thank you for reply; as I already mentioned that I am using phonegap build https://build.phonegap.com/apps ; in this I can only work around in www directory and can't modify any other source code. So modifying java class is not possible in my case.

**Comment by christocracy** [comment]
Modifying a Java class *is* possible in your case.  You've never heard of
"private phone gap plugins"?

You could with this plugin, modify its Java source, rename the pluginID
and submit to PGB as your very own "private plugin".

On Saturday, September 26, 2015, Himanshu Agarwal <notifications@github.com>
wrote:

> Thank you for reply; as I already mentioned that I am using phonegap build
> https://build.phonegap.com/apps ; in this I can only work around in www
> directory and can't modify any other source code. So modifying java class
> is not possible in my case.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/167#issuecomment-143398704>
> .
>


-- 
Snet form Gmail Mobile

**Comment by christocracy** [comment]
Meant to link reference to "phonegap private plugins":

http://stackoverflow.com/questions/18656810/how-to-make-a-custom-private-plugin-in-phonegap


On Saturday, September 26, 2015, Chris Scott <christocracy@gmail.com> wrote:

> Modifying a Java class *is* possible in your case.  You've never heard of
> "private phone gap plugins"?
>
> You could with this plugin, modify its Java source, rename the pluginID
> and submit to PGB as your very own "private plugin".
>
> On Saturday, September 26, 2015, Himanshu Agarwal <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Thank you for reply; as I already mentioned that I am using phonegap
>> build https://build.phonegap.com/apps ; in this I can only work around
>> in www directory and can't modify any other source code. So modifying java
>> class is not possible in my case.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/phonegap/phonegap-plugin-push/issues/167#issuecomment-143398704>
>> .
>>
>
>
> --
> Snet form Gmail Mobile
>


-- 
Snet form Gmail Mobile

**Comment by app2naklabs** [comment]
As you suggested to modify *PushHandlerActivity.java* class with https://github.com/christocracy/push-cordova-plugin/blob/master/src/android/PushHandlerActivity.java#L34 ; I have checked your code https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/PushHandlerActivity.java#L33.

In both it's having same values on that line; so to be specific can you guide me what I need to modify I am getting confused.

**Comment by christocracy** [comment]
Sorry, that's all I've got for you.  You're on your own

On Saturday, September 26, 2015, Himanshu Agarwal <notifications@github.com>
wrote:

> As you suggested to modify *PushHandlerActivity.java* class with
> https://github.com/christocracy/push-cordova-plugin/blob/master/src/android/PushHandlerActivity.java#L34
> ; I have checked your code
> https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/PushHandlerActivity.java#L33
> .
>
> In both it's having same values on that line; so to be specific can you
> guide me what I need to modify I am getting confused.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/167#issuecomment-143399440>
> .
>


-- 
Snet form Gmail Mobile

**Comment by app2naklabs** [comment]
@christocracy I have tried with your method also in which I have modified your java classes as per your suggestion and tried to get the notification when app is not running or force stopped; unfortunately  I am still not able to receive notification in this state. I tried to debug it and find that in your *GCMIntentService* class there's method named *onMessage()* in this I tried to simple *Toast* with static String text, but in that case also when I trigger notification when app is open that Toast appears; whereas if app is closed/not in background and trigger the notification then the Toast is not showing. So I guess their is some issue with *BroadcastReceiver* or in *AndroidManifest.xml* file for receiver in background. 

It would be kind assistance if you can try this case on your side to get exact issue detail. I hope this would help other too for similar kind of issues.

**Comment by christocracy** [comment]
Sorry, can't help you.  I'm not actively using Push in any app currently.

On Monday, September 28, 2015, Himanshu Agarwal <notifications@github.com>
wrote:

> @christocracy <https://github.com/christocracy> I have tried with your
> method also in which I have modified your java classes as per your
> suggestion and tried to get the notification when app is not running or
> force stopped; unfortunately I am still not able to receive notification in
> this state. I tried to debug it and find that in your *GCMIntentService*
> class there's method named *onMessage()* in this I tried to simple *Toast*
> with static String text, but in that case also when I trigger notification
> when app is open that Toast appears; whereas if app is closed/not in
> background and trigger the notification then the Toast is not showing. So I
> guess their is some issue with *BroadcastReceiver* or in
> *AndroidManifest.xml* file for receiver in background.
>
> It would be kind assistance if you can try this case on your side to get
> exact issue detail. I hope this would help other too for similar kind of
> issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phonegap/phonegap-plugin-push/issues/167#issuecomment-143639605>
> .
>


-- 
Snet form Gmail Mobile

**Comment by app2naklabs** [comment]
OK thank you for your kind attention and suggestion. If any further recommendation or suggestions you can provide will be great help for me. 
Thanks allot

**Comment by macdonst** [comment]
@christocracy we gotta sit down for a coffee someday as I'm only 2 hours away from you in Ottawa.

Why not send a PR to this plugin to add the functionality for everyone?

**Comment by christocracy** [comment]
I'm not really working on anything requiring Push these days.  I'm very busy with my [own products](http://shop.transistorsoft.com/pages/cordova-background-geolocation-premium).

Ottawa, eh?  Ever hang out with the folks from Shopify?

**Comment by macdonst** [comment]
@christocracy Going to drop you a email on your gmail account.

**Comment by app2naklabs** [comment]
I have recently updated my config file with gradle support in PhoneGap Build by adding these two into config.xml

<pre> < preference name="android-minSdkVersion" value="14" />
< preference name="android-build-tool" value="gradle" /></pre>

And able to build with latest version of Push plugin; In this version too I am still not able to receive notification if app is completely closed (nor in background, nor in foreground). So I think this might require few enhancement to make it work.

**Comment by abhinavgujjar** [comment]
Was this issue actually resolved? I can see this referencing #194, but that issue is closed and points back to this one.

**Comment by macdonst** [comment]
@abhinavgujjar yes, it was resolved by issue #93.

**Comment by abhinavgujjar** [comment]
Yeah. It wasn't working on my Mi phone because of additional security on
this phone. Thanks!

**Comment by akz92** [comment]
@abhinavgujjar I have the same issue you had with Mi phones. What did you do to solve it?

**Comment by felipecaparelli** [comment]
It is a little confuse... sometimes the service works to receive the message, but a lot of messages aren't received.  But I don't know if it is from GCM or in the push client listener.

**Comment by marcoziegaus** [comment]
I think that by issue #93 only the first and second use case of OP are covered. I still experience trouble to  react to a push notification when the app is closed (killed via task switcher). The notification is shown in the notification bar, but the javascript code in push.on('notification') is not executed.

Am I missing something, or is this currently not supported?

**Comment by victorcarvalhosp** [comment]
I'm having the exact same problem here @marcoziegaus  ...

**Comment by christocracy** [comment]
If the user closes the app via task-switcher, the only way for your Javascript callback to be called would be for the Push service to reboot the app to the foreground.  This may be surprising to the user.  Is that what you want?

**Comment by victorcarvalhosp** [comment]
@christocracy So how I can show a notification when the app is closed? Almost every app do that... I'm starting to work with this, and I'm confused by that =o

**Comment by christocracy** [comment]
(full disclosure:  I have nothing to do with this plugin or PhoneGap)

You say "almost every app do that".  tell me one and show me a screenshot.

**Comment by victorcarvalhosp** [comment]
facebook and twitter app do that. I receive notifications from both even when they are closed

**Comment by christocracy** [comment]
show me a screenshot of these notifications that occurred after you closed the app.

**Comment by victorcarvalhosp** [comment]
Look here:
https://uploaddeimagens.com.br/imagens/screenshot_2016-04-18-11-12-21-png
There's no open app

And here I receive the twitter notification:
https://uploaddeimagens.com.br/imagens/screenshot_2016-04-18-11-17-15-png

**Comment by christocracy** [comment]
So screenshot **#2**:  this is the Android notifications list?

**Comment by victorcarvalhosp** [comment]
yes

**Comment by christocracy** [comment]
There's no reason this Push plugin's background-service cannot  post a Notification to the Android Notification list when a Push is received.

**Comment by christocracy** [comment]
Why don't you post some `adb logcat` logs while receiving a Push with app closed?

**Comment by victorcarvalhosp** [comment]
Using the Device Monitor from android studio I receive the notification on console event the app is closed!
`04-18 13:56:45.300 11256-11256/br.com.nextt.outclass D/ActivityThread: BDC-Calling onReceive: intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=br.com.nextt.outclass cmp=br.com.nextt.outclass/com.google.android.gms.gcm.GcmReceiver (has extras) }, ordered=true, receiver=com.google.android.gms.gcm.GcmReceiver@426d9b80
04-18 13:56:45.330 11256-11256/br.com.nextt.outclass D/ActivityThread: BDC-RECEIVER handled : 0 / ReceiverData{intent=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=br.com.nextt.outclass cmp=br.com.nextt.outclass/com.adobe.phonegap.push.GCMIntentService (has extras) } packageName=br.com.nextt.outclass resultCode=-1 resultData=null resultExtras=null}
04-18 13:56:45.330 11256-11256/br.com.nextt.outclass D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@426db148 className=com.adobe.phonegap.push.GCMIntentService packageName=br.com.nextt.outclass intent=null}
04-18 13:56:45.331 11256-11256/br.com.nextt.outclass D/ActivityThread: SVC-CREATE_SERVICE handled : 0 / CreateServiceData{token=android.os.BinderProxy@426db148 className=com.adobe.phonegap.push.GCMIntentService packageName=br.com.nextt.outclass intent=null}
04-18 13:56:45.331 11256-11256/br.com.nextt.outclass D/ActivityThread: SVC-Calling onStartCommand: com.adobe.phonegap.push.GCMIntentService@426dcc28, flags=0, startId=1
04-18 13:56:45.333 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: onMessage - from: 86747193650
04-18 13:56:45.333 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: normalize extras
04-18 13:56:45.333 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: key = sendOn
04-18 13:56:45.334 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: replace key sendOn with sendOn
04-18 13:56:45.334 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: key = ids
04-18 13:56:45.334 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: replace key ids with ids
04-18 13:56:45.334 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: key = msgType
04-18 13:56:45.334 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: replace key msgType with msgType
04-18 13:56:45.334 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: key = collapse_key
04-18 13:56:45.334 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: replace key collapse_key with collapse_key
04-18 13:56:45.335 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: background
04-18 13:56:45.335 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: message =[null]
04-18 13:56:45.335 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: title =[null]
04-18 13:56:45.335 11256-11278/br.com.nextt.outclass D/PushPlugin_GCMIntentService: contentAvailable =[null]
04-18 13:56:45.343 11256-11256/br.com.nextt.outclass D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@426db148 startId=1 args=Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x10 pkg=br.com.nextt.outclass cmp=br.com.nextt.outclass/com.adobe.phonegap.push.GCMIntentService (has extras) }}
04-18 13:56:45.344 11256-11256/br.com.nextt.outclass D/ActivityThread: SVC-Destroying service: com.adobe.phonegap.push.GCMIntentService@426dcc28
04-18 13:56:45.346 11256-11256/br.com.nextt.outclass D/ActivityThread: SVC-STOP_SERVICE handled : 0 / android.os.BinderProxy@426db148`

But the  push.on('notification', (data) => {...} is never called when the app is closed or minimized...

**Comment by christocracy** [comment]
Assuming this is Javascript:
```
push.on('notification', (data) => {...}
```

Why do you expect you Javascript callback to execute **IF THE APP IS CLOSED**??

**Comment by victorcarvalhosp** [comment]
I think the plugin would take care of this. If you see in the log he shows the package of the project... 
So I think, in some way, is possible to do this... If the plugin don't do this, how can I do?

Thanks

**Comment by christocracy** [comment]
It is possible to have a background-service boot the foreground Activity (where your javascript lives).  I do this sort of thing in my [Background Geolocation plugin](https://github.com/transistorsoft/cordova-background-geolocation-lt).

**Comment by christocracy** [comment]
The plugin does have [forceMainActivityReload](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/PushHandlerActivity.java#L72) method.  It *does* seem to have the ability to boot the foreground Activity.

**Comment by christocracy** [comment]
`forceMainActivityReload` is executed [here](https://github.com/phonegap/phonegap-plugin-push/blob/master/src/android/com/adobe/phonegap/push/PushHandlerActivity.java#L43)

**Comment by christocracy** [comment]
I think that logic is unusual.  I would expect the plugin is able to force the main activity to reload (if app was closed) simply by receiving a Push in the background.  It should be configurable too.

eg: 

```
PushNotification.init({
  forceReload: true,  // <-- If app is closed when a bg push is received, force main activity to boot.
  .
  .
  .
});
```

**Comment by santhoshscs** [comment]
Is the third case fully resolved ?

> Third; If my app is completely closed means no background or foreground, then if I trigger a push notification from server then nothing happens inside my app. I have tested this case with n number of push notifications but none of it worked.

When I tried I was able to get case1 , case 2, case 3 working on ios . But for Android case1 , case 2 works 
But no luck on  case3 (ie app fully closed status)

**Comment by engagedmorales** [comment]
Guys,

I have faced this problem for days, and fixed that just adding priority: "high" in the objectt sent to Notifications Service.

Now, my app on IOS shows me notification even the app is killed (closed).

**Comment by midhunadarvin** [comment]
Same issue as of #158 , Can any body help? This is a huge problem as the app will get killed by the android OS itself. The notification handler doesn't work if the web view inside the app is restarted.
