### ISSUE TITLE
Android notifications not working at all like described in your docs

### ISSUE THREAD

**Issue by einicher** [phonegap/phonegap-plugin-push#606]
What partially works for me now:
```
{
        "registration_ids": [
            "XXX"
        ],
        "notification": {
            "title": "test_title_1",
            "body": "bodytext 9",
            "sound": "default"
        },
        "data": {
            "data_key": "data_value",
            "title": "test_title_2",
            "message": "test_message",
            "notId": 9,
            "content_available": "1",
            "info": "test_push_9"
        }
}
```

Without the notification object in my json the phones just vibrate and make sound but do not show any notifications ever. With the notification object in the server json i get a notification always (with sound, no vibrate), since i read several issues here i understand it is because the the phone takes them over directly, meaning your plugin is not processing them.
Although i have content_available (or content-available) which as i understand works around that problem, the notification event is not triggered when you touch on the notification. The app opens, but notification event is not called.

As i understand the simple code
```
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "title",
        "message": "message"
    }
}
```
should already show up a notification. But it does not.
What is the correct way to handle this now?
As i understand, i shouldn't need the notification{} in my server json at all, the plugin should handle it.

Am I getting something wrong, or is it simply not working?

init:
```
	var push = PushNotification.init({
		android: {
		    senderID: 'XXX',
		    forceShow: true,
		    sound: true,
		    vibrate: true,
		    iconColor: '#369'
		},
		ios: {
		    alert: "true",
		    badge: "true",
		    sound: "true"
		},
		windows: {}
	});
```

**Comment by macdonst** [comment]
@einicher if you send:

```
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "title",
        "message": "message"
    }
}
```

when the app is in the background you should get a notification in the shade. When the app is in the foreground you should get your `on('notification')` handler called.

If you are not seeing this can you reproduce the problem while running `adb logcat | grep PushPlugin` and show me the logs?

**Comment by vodvud** [comment]
Hello!
I have a similar problem to the device do not get the message, I can not understand why?

Messages that I send are only accepted on the GCM server
https://dl.dropboxusercontent.com/u/75861562/Selection_2016.01.28_23%3A58%3A29.png

**Comment by macdonst** [comment]
@vodvud are you specifying your own sender ID?

**Comment by vodvud** [comment]
Yes of course.

**Comment by einicher** [comment]
@macdonst 
```
D/PushPlugin_GCMIntentService(29736): onMessage - from: 684734748562
D/PushPlugin_GCMIntentService(29736): normalize extras
D/PushPlugin_GCMIntentService(29736): key = title
D/PushPlugin_GCMIntentService(29736): replace key title with title
D/PushPlugin_GCMIntentService(29736): key = message
D/PushPlugin_GCMIntentService(29736): replace key message with message
D/PushPlugin_GCMIntentService(29736): key = collapse_key
D/PushPlugin_GCMIntentService(29736): replace key collapse_key with collapse_key
D/PushPlugin_GCMIntentService(29736): foreground force
D/PushPlugin_GCMIntentService(29736): message =[message]
D/PushPlugin_GCMIntentService(29736): title =[title]
D/PushPlugin_GCMIntentService(29736): contentAvailable =[null]
D/PushPlugin_GCMIntentService(29736): create notification
E/PushPlugin_GCMIntentService(29736): Number format exception - Error parsing notId: Invalid int: "null"
D/PushPlugin_GCMIntentService(29736): stored icon=null
D/PushPlugin_GCMIntentService(29736): stored iconColor=#369
D/PushPlugin_GCMIntentService(29736): stored sound=true
D/PushPlugin_GCMIntentService(29736): stored vibrate=true
E/PushPlugin_GCMIntentService(29736): couldn't parse color from android options
D/PushPlugin_GCMIntentService(29736): no icon resource found - using application icon
D/PushPlugin_GCMIntentService(29736): create actions
```

**Comment by vodvud** [comment]
The problem was solved, it was necessary to add a required parameter **title**
like this
`
{
  "registration_ids": [
    "eR5UWH208Us:APA91bEfh2E-T6N2iMGjYBjCs6G9sBUtMWIk9jLEdm3E2HltMMzF0FHMCcbo6I49wJJxZzrarUOMsvC8iCtoc17tFQ7NvuO4dBPouJeCzY_voge57eBwZNw8qtTb3-D3rzpjD1w14elF"
  ],
  "data": {
      "title": "title",
      "message": "This is a GCM Topic Message!!!"
  }
}
`

but I did earlier like this
`
{
  "registration_ids": [
    "eR5UWH208Us:APA91bEfh2E-T6N2iMGjYBjCs6G9sBUtMWIk9jLEdm3E2HltMMzF0FHMCcbo6I49wJJxZzrarUOMsvC8iCtoc17tFQ7NvuO4dBPouJeCzY_voge57eBwZNw8qtTb3-D3rzpjD1w14elF"
  ],
  "data": {
      "message": "This is a GCM Topic Message!!!"
  }
}
`

**Comment by kilombo** [comment]
@einicher I have the same issue.
@macdonst I receive the alert on my device only when is foreground. When its on background, the tablet only vibrates, but is not showing nothing on the notifications bar. 

My code on server:
```
$msg = array
(
'title' => $title,
'message' => $message,
'vibrate' => 1,
'sound' => 1,
'content-available' => 1
// you can also add images, additionalData
);
$notification = array(
	'title' => "TEST TITLE",
	'body' => "TEST BODY"
);
$fields = array
(
'registration_ids' => $registrationIds,
'notification' => $notification,
'data' => $msg
);
$headers = array
(
'Authorization: key=' . API_ACCESS_KEY,
'Content-Type: application/json'
);
$ch = curl_init();
curl_setopt( $ch,CURLOPT_URL, 'https://android.googleapis.com/gcm/send' );
curl_setopt( $ch,CURLOPT_POST, true );
curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
$result = curl_exec($ch );
curl_close( $ch );
echo $result;
```

My code on index.html
```
<script type="text/javascript">
    document.addEventListener("deviceready",onDeviceReady,false);
    function onDeviceReady(){
      console.log("Device Ready")
      var push = PushNotification.init(
        {
          "android": {
            senderID: "my12numbers"
          },
          "ios": {"alert": "true", "badge": "true", "sound": "true"},
          "windows": {}
        }
      );

      push.on('registration', function(data) {
      console.log(data.registrationId);
      $("#gcm_id").html(data.registrationId);
      });

      push.on('notification', function(data) {
        console.log(data.message);
        alert(data.title+" Message: " +data.message);
        // data.title,
        // data.count,
        // data.sound,
        // data.image,
        // data.additionalData
      });

      push.on('error', function(e) {
      console.log(e.message);
      });

      if(device.platform == "iOS"){
        $('body').addClass('iOS');
      }
    }
    </script>
```

**Comment by kilombo** [comment]
Solved, added "priority" : "high" and the push works on background, please add this on a **h1** on the Examples section or on a visible place XD

```
$fields = array
(
'registration_ids' => $registrationIds,
'priority' => "high",
'data' => $msg
);
```

**Comment by einicher** [comment]
Not solved. Since it has nothing to do with the topic.
Topic is: there is a docmunetation which does not work at all. Basically.

**Comment by macdonst** [comment]
@einicher I can't reproduce your problem. Please make sure you put all the push data in the `data` part of the push. The `notification` object is handled by the OS and screws with the plugin.

**Comment by einicher** [comment]
i send one push with priority:high, then it suddenly worked. Removed the priority:high again and it still works. weird.
